
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SplashCursor from "@/components/SplashCursor";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <SplashCursor />
        <div className="relative z-10">
          <Navbar className="absolute inset-x-0 top-0 z-50" />
          {children}
        </div>
      </body>
    </html>
  );
}
