
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" ">
        {/* Optimized background image */}
           <Image
             src="/img/bg.jpg"
             alt="Aurora background"
             fill
             priority
             quality={60}
             sizes="100vw"
             style={{
               objectFit: "cover",
               zIndex: -1,
               pointerEvents: "none",
               userSelect: "none",
             }}
           />
        <div className="relative z-10">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
